[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TravianBotSharp"
authors = [{name = "VINAGHOST", email = "nguyentrungnhan87(at)gmail.com"}]
dynamic = ["version", "description"]
